import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {useQuery} from '@apollo/client';
import productByIdQuery from "../queries/product";
import Loader from "../components/Loader";
import ProductOptions from '../components/ProductOptions';

const Home: NextPage = () => {
    const {loading, error, data} = useQuery(productByIdQuery);

    if (loading) return <Loader/>
    if (error) return <p>Error :( {error.message}</p>;
    if (!data) return null;

    const {title, image: {src, alt, width, height}, options, variants} = JSON.parse(data.productById.data);

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <div className="bg-orange-200 mb-14 rounded-b-xl py-7 px-4">
                    <h1>{title}</h1>
                </div>
               <div className="px-28 pb-24 max-w-screen-md w-full m-auto">
                   <Image
                       src={src}
                       alt={alt}
                       width={width}
                       height={height}
                   />
                   <ProductOptions options={options} variants={variants}/>
                   <button className="text-xl bg-gradient-to-b from-amber-500 to-amber-600 text-center m-auto w-full rounded-md text-white mt-14 h-16">Add to My Store</button>
               </div>
            </main>

            <footer>

            </footer>
        </div>
    )
}

export default Home
