import type {NextPage} from 'next'
import Head from 'next/head'
import {useQuery} from '@apollo/client';
import productByIdQuery from "../queries/product";
import Loader from "../components/Loader";
import Product from "../components/Product";

const Home: NextPage = () => {
    const {loading, error, data} = useQuery(productByIdQuery);

    if (loading) return <Loader/>
    if (error) return <p>Error :( {error.message}</p>;
    console.log('JSON.parse(data.productById.data):', JSON.parse(data.productById.data) );
    console.log('JSON.parse(data.productById.variantRewards):', JSON.parse(data.productById.variantRewards) );

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <Product productById={data.productById}/>
            </main>

            <footer>

            </footer>
        </div>
    )
}

export default Home
