import type {NextPage} from 'next'
import Head from 'next/head'
import {gql, useQuery} from '@apollo/client';
import Loader from "../components/Loader";
import Product from "../components/Product";

const PRODUCT_BY_ID_QUERY = gql`
  query {
    productById(productId: 53) {
      id
      name
      data
      variantRewards
    }
  }
`

const Home: NextPage = () => {
    const {loading, error, data} = useQuery(PRODUCT_BY_ID_QUERY);

    if (loading) return <Loader/>
    if (error) return <p>Error :( {error.message}</p>;

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <Product productById={data.productById}/>
            </main>

            <footer>

            </footer>
        </div>
    )
}

export default Home
